<a href="https://colab.research.google.com/github/StillWork/additional/blob/master/kepco_69_sum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
x = np.arange(12) ; x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x = x.reshape(6,2) ;x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
y = np.random.randint(0,2,6) ;y

array([1, 1, 0, 0, 1, 0])

In [24]:
np.vstack((x.T,y)).T

array([[ 0,  1,  1],
       [ 2,  3,  1],
       [ 4,  5,  0],
       [ 6,  7,  0],
       [ 8,  9,  1],
       [10, 11,  0]])

In [41]:
x = np.arange(24).reshape(4,6) ;x
# 가로, 세로 합계를 구해서 행과 열을 추가
# ndarray 에서 직접 구현, 또는 DataFrame을 만들어서 구현하는 방법

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
x1 = np.vstack((x, x.sum(0))); x1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [36, 40, 44, 48, 52, 56]])

In [43]:
x2 = np.vstack((x1.T, x1.sum(1))).T ; x2

array([[  0,   1,   2,   3,   4,   5,  15],
       [  6,   7,   8,   9,  10,  11,  51],
       [ 12,  13,  14,  15,  16,  17,  87],
       [ 18,  19,  20,  21,  22,  23, 123],
       [ 36,  40,  44,  48,  52,  56, 276]])

In [52]:
import pandas as pd
df = pd.DataFrame(x) ;df

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23

In [56]:
y = df.sum()
type(y)
y.values

array([36, 40, 44, 48, 52, 56])

In [58]:
df.values # 데이터프레임을 어레이로 변환

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [59]:
df1 = df.append(df.sum(), ignore_index=True); df1

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  36  40  44  48  52  56

In [60]:
df1.sum(1)

0     15
1     51
2     87
3    123
4    276
dtype: int64

In [61]:
df1['6'] = df1.sum(1) ; df1

0   1   2   3   4   5    6
0   0   1   2   3   4   5   15
1   6   7   8   9  10  11   51
2  12  13  14  15  16  17   87
3  18  19  20  21  22  23  123
4  36  40  44  48  52  56  276